import Header from '@/components/main-header';
import Footer from '@/components/footer';

import "./globals.css";

export const metadata = {
  title: "הזמנת לחם - לחם הדסה",
  description: "Generated by create next app"
};

export const viewport = {
  themeColor: "#886642"
};

export default function RootLayout({ children }) {
  return (
    <html lang="he">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
